server:
  port: 8080

# --- Datasource ---
spring:

  main:
    allow-bean-definition-overriding: false

  datasource:
    #url: jdbc:postgresql://db-seblog:5433/seblog
    url: jdbc:postgresql://localhost:5433/seblog?currentSchema=public
    username: seblog
    password: seblogpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min idle: 0
          max-wait: -1ms

# --- Liquibase ---
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true

redis:
  ttl-hours: 24

# --- Logging ---
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.hibernate.sql: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [requestId:%X{requestId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [requestId:%X{requestId}] - %msg%n"

  level:
    ru.sshibko.backend_seblog: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN

  file:
    name: logs/application.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30

# --- Management (Actuator) ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# --- Security ---

jwt:
  secret: "mySecretKeyForJWTGenerationThatIsAtLeast256BitsLongForSecurity"
  access-token-expiration: 900000 # 15 min
  refresh-token-expiration: 604800000 # 7 days

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          secret-value: ${jwt.secret}